### ISSUE TITLE
Possible FAQ entry or just an extension for the main README: use cases for zeroconf?

### ISSUE THREAD

**Issue by rubyFeedback** [tenderlove/zeroconf#2]
Hey there tenderlove,

If you feel motivated and have some time, would you perhaps consider adding
either a FAQ to zeroconf, or simply extend the main README, or if you feel it may
fit better, onto the wiki on github here?

Either way one FAQ entry or extension to the main README, would be my question
as to **what the use case of zeroconf is**.

When I first read the main README here, I thought it was dhcpcd in ruby, but upon rereading it,
I think I may have misunderstood it, because the examples you show have to do more
**with finding a service automatically** (whereas dhcpcd would be to obtain the
primary DNS / IP connection and connect to the world wide web via router)
So I may have misunderstood the use case for zeroconf. So what is the primary
use case for zeroconf, aka, why may we need it? Could the main README 
explain on the primary use case a bit more for people like me who often 
have a hard time initially understanding things? Thank you for reading
this and potentially considering the issue request.

**Comment by tenderlove** [comment]
If you have suggestions for how to improve the readme, I would appreciate any patches you can send. My assumption is that users will do some homework about the uses for multicast DNS on their own before trying to consume this library. In other words, explaining the use cases for a multicast DNS client / server seems (at least to me) to be out of scope.
